name: My shop
favicon: null
layout_spectrum: 0.6257680712733418
typography_spectrum: 0.8211740122642368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171528'
    - '#b48bcd'
    - '#dfdacf'
    - '#3c3851'
    - '#716d73'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.9414637880399823
purpose: []
